move  aleppo.map         D:\us_mod_geog\geog\middle
move  al_wadi.map        D:\us_mod_geog\geog\middle
move  al_quaan.map   	D:\us_mod_geog\geog\middle
move  tulunid.map      	D:\us_mod_geog\geog\middle
move  saladin.map        D:\us_mod_geog\geog\middle
move  nureddin.map       D:\us_mod_geog\geog\middle
move  hant.map           D:\us_mod_geog\geog\middle
move  akra.map           D:\us_mod_geog\geog\middle
move  epitaph.map        D:\us_mod_geog\geog\middle
move  lombard.map        D:\us_mod_geog\geog\middle
move  ripon.map          D:\us_mod_geog\geog\middle
move  nisami.map         D:\us_mod_geog\geog\middle
move  corliss.map        D:\us_mod_geog\geog\middle
move  watts.map          D:\us_mod_geog\geog\middle
move  kronholm.map       D:\us_mod_geog\geog\middle
move  li_po.map          D:\us_mod_geog\geog\middle
move  tau_tsun.map       D:\us_mod_geog\geog\middle
move  xu_xuan.map        D:\us_mod_geog\geog\middle
move  providence.map     D:\us_mod_geog\geog\middle
move  emerald_sys.map    D:\us_mod_geog\geog\middle
move  penda.map          D:\us_mod_geog\geog\middle
move  huang.map          D:\us_mod_geog\geog\middle
move  bumpys_star.map    D:\us_mod_geog\geog\middle
move  alcuin.map         D:\us_mod_geog\geog\middle
move  bedalov.map        D:\us_mod_geog\geog\middle
move  powys.map          D:\us_mod_geog\geog\middle
move  t_ang.map          D:\us_mod_geog\geog\middle
move  x472.map           D:\us_mod_geog\geog\middle
move  hd3479.map         D:\us_mod_geog\geog\middle
move  hd3887.map         D:\us_mod_geog\geog\middle
move  hd2271.map         D:\us_mod_geog\geog\middle
move  al42217.map        D:\us_mod_geog\geog\middle
move  al43844.map        D:\us_mod_geog\geog\middle
move  hd4045.map         D:\us_mod_geog\geog\middle
move  x788.map           D:\us_mod_geog\geog\middle
move  al40064.map        D:\us_mod_geog\geog\middle
move  al43551.map        D:\us_mod_geog\geog\middle
move  al43665.map        D:\us_mod_geog\geog\middle
move  capsule_space.map  D:\us_mod_geog\geog\middle



move  aleppo.ini         D:\us_mod_geog\geog\middle
move  al_wadi.ini        D:\us_mod_geog\geog\middle
move  al_quaan.ini   D:\us_mod_geog\geog\middle
move  tulunid.ini      D:\us_mod_geog\geog\middle
move  saladin.ini        D:\us_mod_geog\geog\middle
move  nureddin.ini       D:\us_mod_geog\geog\middle
move  hant.ini           D:\us_mod_geog\geog\middle
move  akra.ini           D:\us_mod_geog\geog\middle
move  epitaph.ini        D:\us_mod_geog\geog\middle
move  lombard.ini        D:\us_mod_geog\geog\middle
move  ripon.ini          D:\us_mod_geog\geog\middle
move  nisami.ini         D:\us_mod_geog\geog\middle
move  corliss.ini        D:\us_mod_geog\geog\middle
move  watts.ini          D:\us_mod_geog\geog\middle
move  kronholm.ini       D:\us_mod_geog\geog\middle
move  li_po.ini          D:\us_mod_geog\geog\middle
move  tau_tsun.ini       D:\us_mod_geog\geog\middle
move  xu_xuan.ini        D:\us_mod_geog\geog\middle
move  providence.ini     D:\us_mod_geog\geog\middle
move  emerald_sys.ini    D:\us_mod_geog\geog\middle
move  penda.ini          D:\us_mod_geog\geog\middle
move  huang.ini          D:\us_mod_geog\geog\middle
move  bumpys_star.ini    D:\us_mod_geog\geog\middle
move  alcuin.ini         D:\us_mod_geog\geog\middle
move  bedalov.ini        D:\us_mod_geog\geog\middle
move  powys.ini          D:\us_mod_geog\geog\middle
move  t_ang.ini          D:\us_mod_geog\geog\middle
move  x472.ini           D:\us_mod_geog\geog\middle
move  hd3479.ini         D:\us_mod_geog\geog\middle
move  hd3887.ini         D:\us_mod_geog\geog\middle
move  hd2271.ini         D:\us_mod_geog\geog\middle
move  al42217.ini        D:\us_mod_geog\geog\middle
move  al43844.ini        D:\us_mod_geog\geog\middle
move  hd4045.ini         D:\us_mod_geog\geog\middle
move  x788.ini           D:\us_mod_geog\geog\middle
move  al40064.ini        D:\us_mod_geog\geog\middle
move  al43551.ini        D:\us_mod_geog\geog\middle
move  al43665.ini        D:\us_mod_geog\geog\middle
move  capsule_space.ini  D:\us_mod_geog\geog\middle



move  aleppo.txt         D:\us_mod_geog\TEXT\geog\aleppo.csv
move  al_wadi.txt        D:\us_mod_geog\TEXT\geog\al_wadi.csv
move  al_quaan.txt   D:\us_mod_geog\TEXT\geog\al_quaan.csv
move  tulunid.txt      D:\us_mod_geog\TEXT\geog\tulunid.csv
move  saladin.txt        D:\us_mod_geog\TEXT\geog\saladin.csv
move  nureddin.txt       D:\us_mod_geog\TEXT\geog\nureddin.csv
move  hant.txt           D:\us_mod_geog\TEXT\geog\hant.csv
move  akra.txt           D:\us_mod_geog\TEXT\geog\akra.csv
move  epitaph.txt        D:\us_mod_geog\TEXT\geog\epitaph.csv
move  lombard.txt        D:\us_mod_geog\TEXT\geog\lombard.csv
move  ripon.txt          D:\us_mod_geog\TEXT\geog\ripon.csv
move  nisami.txt         D:\us_mod_geog\TEXT\geog\nisami.csv
move  corliss.txt        D:\us_mod_geog\TEXT\geog\corliss.csv
move  watts.txt          D:\us_mod_geog\TEXT\geog\watts.csv
move  kronholm.txt       D:\us_mod_geog\TEXT\geog\kronholm.csv
move  li_po.txt          D:\us_mod_geog\TEXT\geog\li_po.csv
move  tau_tsun.txt       D:\us_mod_geog\TEXT\geog\tau_tsun.csv
move  xu_xuan.txt        D:\us_mod_geog\TEXT\geog\xu_xuan.csv
move  providence.txt     D:\us_mod_geog\TEXT\geog\providence.csv
move  emerald_sys.txt    D:\us_mod_geog\TEXT\geog\emerald_sys.csv
move  penda.txt          D:\us_mod_geog\TEXT\geog\penda.csv
move  huang.txt          D:\us_mod_geog\TEXT\geog\huang.csv
move  bumpys_star.txt    D:\us_mod_geog\TEXT\geog\bumpys_star.csv
move  alcuin.txt         D:\us_mod_geog\TEXT\geog\alcuin.csv
move  bedalov.txt        D:\us_mod_geog\TEXT\geog\bedalov.csv
move  powys.txt          D:\us_mod_geog\TEXT\geog\powys.csv
move  t_ang.txt          D:\us_mod_geog\TEXT\geog\t_ang.csv
move  x472.txt           D:\us_mod_geog\TEXT\geog\x472.csv
move  hd3479.txt         D:\us_mod_geog\TEXT\geog\hd3479.csv
move  hd3887.txt         D:\us_mod_geog\TEXT\geog\hd3887.csv
move  hd2271.txt         D:\us_mod_geog\TEXT\geog\hd2271.csv
move  al42217.txt        D:\us_mod_geog\TEXT\geog\al42217.csv
move  al43844.txt        D:\us_mod_geog\TEXT\geog\al43844.csv
move  hd4045.txt         D:\us_mod_geog\TEXT\geog\hd4045.csv
move  x788.txt           D:\us_mod_geog\TEXT\geog\x788.csv
move  al40064.txt        D:\us_mod_geog\TEXT\geog\al40064.csv
move  al43551.txt        D:\us_mod_geog\TEXT\geog\al43551.csv
move  al43665.txt        D:\us_mod_geog\TEXT\geog\al43665.csv
move  capsule_space.txt        D:\us_mod_geog\TEXT\geog\capsule_space.csv
